# Scikit Learn Exercise   AI240 - 10459
## Rob Taylor 4/23/25
Instructor - Dr. Uma Gajendragadkar

## Exercise 1 - 
First install Numpy Library (if it's not already installed) as it is required by Scikit Learn Library.


## Exercise 2 - 
First import pandas and numpy with below statements


## Exercise 3 - 
Load default datsets - the iris dataset with below statetments.


## Exercise 4 - 
Lets's use IRIS dataset and execute below lines of code and check the output.


## Exercise 5 - 
Splitting the dataset
Split the dataset into two pieces-a training set and a testing set. Use the training set to train the model and testing set to test the model. Execute below lines of code to split the data into 80:20 ratio . It means 80% data is training data and 20% as testing data.

## Exercise 6 - 
Train the Model
Use our dataset to train some prediction-model. Scikit-learn has wide range of Machine Learning (ML) algorithms.

Here, we are going to use KNN (K nearest neighbors) classifier for sake of learning the scikit Library. We are going to learn classification in detail in coming weeks. Below lines of code are to be executed and are used to make you understand the implementation. 



In [2]:
### Exercise 1 (installations)
!pip install numpy

In [3]:
!pip install scikit-learn

In [4]:
pip show scikit-learn

Name: scikit-learn
Version: 1.5.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: C:\Users\robta\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn
Note: you may need to restart the kernel to use updated packages.


In [5]:
### Exercise 2 (imports)
# Import pandas and numpy with below statements 
import numpy as np 
import pandas as pd
import sklearn
from sklearn import datasets

In [18]:
### Exercise 3 (load the datasets)
# Load default datsets - the iris dataset with below statetments.
iris = datasets.load_iris()

In [7]:
### Exercise 4 (check the output)
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

feature_names = iris.feature_names
target_names = iris.target_names

print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [8]:
### Exercise 5 (Split the data)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [9]:
### Exercise 6 (Train the Model)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

classifier_knn = KNeighborsClassifier(n_neighbors = 5)
classifier_knn.fit(X_train, y_train)

y_pred = classifier_knn.predict(X_test)

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0
