# Numpy Exercise for AI 240  - 10459          
## Rob Taylor 4/23/2025

Instructor- Dr. Uma Gajendragadkar

### Save and submit your notebook in your Github account.

In [2]:
### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy  

In [3]:
### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

In [4]:
### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [5]:
### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

In [24]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [20]:
arr1 = np.array([[10,20,30],[40,50,60]])
print(arr1)

[[10 20 30]
 [40 50 60]]


In [26]:
print(arr[0])

10


In [28]:
print(arr[1:5])

[20 30 40 50]


In [30]:
arr = np.array([40,30,20,10,50])
print(np.sort(arr))

[10 20 30 40 50]


In [32]:
arr = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr))

['berry' 'kiwi' 'pear']


In [7]:
### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

# Find the indexes where the value is 9:

arr = np.array([3, 2, 14, 9, 10, 12])
indices = np.where(arr == 9)[0]

print("original array: ", arr)
print("Indicies where value = 9 : ", indices)

original array:  [ 3  2 14  9 10 12]
Indicies where value = 9 :  [3]


In [8]:
### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])

# use np.concatenate
concatenated = np.concatenate((arr1, arr2))
print("Concatenated:", concatenated)

# or np.append
appended = np.append(arr1, arr2)
print("Appended:", appended)


Concatenated: [ 9  5  8 55 89 76]
Appended: [ 9  5  8 55 89 76]
